set number

colorscheme wildcharm

syntax on

filetype on
filetype plugin on
filetype indent on

set tabstop=4
set shiftwidth=4

set wildmenu
set hidden "allow switch buffer with unsaved changes

set guifont=Consolas:h14

set guioptions-=m "hide menu bar
set guioptions-=T "hide toolbar
set guioptions-=r "hide scrollbar

set cursorline
set termguicolors

set spell
set spelllang=en,pt_br

set incsearch

set ignorecase
set smartcase

set ruler

packadd! matchit "extended '%' matching
